'use strict';

/*
 * js/common.js の @shared ブロックを functions/src/lib/bingo.js として
 * CommonJS 化する同期スクリプト。カード生成・ライン判定ロジックを
 * ブラウザ(v1/v2 フロントエンド)と Cloud Functions で単一ソースにするための橋渡し。
 * 実行タイミング: npm test の pretest / firebase deploy の predeploy
 */

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', '..', 'js', 'common.js');
const DEST = path.join(__dirname, '..', 'src', 'lib', 'bingo.js');
const START_MARK = '/* @shared:start */';
const END_MARK = '/* @shared:end */';

function main() {
  const src = fs.readFileSync(SRC, 'utf8');
  const startIdx = src.indexOf(START_MARK);
  const endIdx = src.indexOf(END_MARK);
  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    throw new Error(
      'sync-lib: js/common.js に @shared:start / @shared:end マーカーが見つかりません'
    );
  }

  const body = src.slice(startIdx + START_MARK.length, endIdx).trim();

  const header =
    '// AUTO-GENERATED by functions/scripts/sync-lib.js — 手編集しないこと\n' +
    '// 元ソース: js/common.js の @shared ブロック(単一ソース)\n' +
    "'use strict';\n\n";

  const footer = '\n\nmodule.exports = QRB_SHARED;\n';

  fs.mkdirSync(path.dirname(DEST), { recursive: true });
  fs.writeFileSync(DEST, header + body + footer);
  console.log('sync-lib: wrote', path.relative(process.cwd(), DEST));
}

main();
